### ISSUE TITLE
restore_host should not be mandatory for an on demand snapshot

### ISSUE THREAD

**Issue by tarunactivity** [rubrik-devops/ansible-rubrik#13]
We should not have to specify restore_host for the action rubrik_snapshot (line 251)

https://github.com/rubrik-devops/ansible-rubrik/blob/2eb825eaab0eb5e78c34593a056903aa9976aaa2/library/rubrik_snapshot.py#L246-L255

**Comment by drew-russell** [comment]
@tarunactivity this has been fixed in our devel branch https://github.com/rubrik-devops/ansible-rubrik/blob/devel/library/rubrik_snapshot.py which will be merged into master after a few internal testing initiatives are completed.
