### ISSUE TITLE
Error during instant_recovery due to timezone API call

### ISSUE THREAD

**Issue by tarunactivity** [rubrik-devops/ansible-rubrik#14]
https://github.com/rubrik-devops/ansible-rubrik/blob/master/library/rubrik_snapshot.py#L172-L177

Both api/v1 and api/internal fail with an HTTP 406 error

tta:logs tta$ curl -X GET --header 'Accept: application/json' 'https://10.35.36.150/api/v1/cluster/me/timezone' -k -H "Authorization: Bearer 58ac371a-395/timezone4-439f-bebb-29265e02068e" -I
HTTP/1.1 406 Not Acceptable
Server: spray-can/1.3.3
Date: Thu, 12 Apr 2018 10:31:15 GMT
Content-Type: text/plain; charset=UTF-8
Content-Length: 104

tta:logs tta$ curl -X GET --header 'Accept: application/json' 'https://10.35.36.150/api/internal/cluster/me/timezone' -k -H "Authorization: Bearer 58ac371a-395/timezone4-439f-bebb-29265e02068e" -I
HTTP/1.1 406 Not Acceptable
Server: spray-can/1.3.3
Date: Thu, 12 Apr 2018 10:31:59 GMT
Content-Type: text/plain; charset=UTF-8
Content-Length: 104

**Comment by drew-russell** [comment]
fixed in the latest modules
