### ISSUE TITLE
Issue with cluster_info.yml

### ISSUE THREAD

**Issue by tarunactivity** [rubrik-devops/ansible-rubrik#2]
```
rksupport@ubuntu:~/work/ansible-rubrik$ ansible-playbook cluster_info.yml 
 [WARNING]: provided hosts list is empty, only localhost is available

ERROR! no action detected in task

The error appears to have been in '/home/rksupport/work/ansible-rubrik/cluster_info.yml': line 4, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
    - name: Test connection to Rubrik
      ^ here
```

Looking at the commit history, the python module, and the yml file were renamed from test_conn to cluster_info , but the method name was not updated.

https://github.com/rubrik-devops/ansible-rubrik/commit/6e713ad2ac22faae6433c6311d6ce5af5d6b6874

Fix: Rename the method to cluster_info - PR : https://github.com/rubrik-devops/ansible-rubrik/pull/1

**Comment by drew-russell** [comment]
The modules have been rewritten which should solve this issue.
